### ISSUE TITLE
angular2-runtime 0.5.0 error

### ISSUE THREAD

**Issue by twastvedt** [Urigo/angular2-meteor#294]
I just upgraded packages and have the following errors in the console when running my app:

```
Uncaught Error: Cannot find module 'angular2-meteor-polyfills/browser'
Uncaught reflect-metadata shim is required when using class decorators
```

I've found that if I downgrade angular2-runtime to `0.2.3_2` then everything works. Any thoughts? Thanks!

**Comment by twastvedt** [comment]
It works with 0.5.0 if I `npm install angular2-meteor-polyfills`. The documentation makes it seem like this shouldn't be necessary though:

> you can install barbatus:angular2-runtime, a package that adds all the required dependencies. Since it's a package, it's loaded by Meteor before any user code.

> 
If you prefer to install polyfills manually for some reason, you can try angular2-meteor-polyfills NPM.

**Comment by barbatus** [comment]
Yes, 0.5.0 is designated for the next version of Angular2-Meteor. angular2-meteor-polyfills is added as dependency in the master https://github.com/Urigo/angular2-meteor/blob/master/package.json#L32.
Some people had issues with the prev version of angular-runtime, so I released 0.5.0 kinda ahead of time. I thought it's not hard to guess with the message `Cannot find module`, that one needs to install this NPM. But it turns out most people can't get it.

**Comment by twastvedt** [comment]
Ok, good to know. I agree that it's not hard to troubleshoot. I was just pointing out that it contradicts the documentation. I thought one of the goals of the documentation was to provide a setup guide that didn't result in errors.
