### ISSUE TITLE
Blank page after updating from angular2-meteor 0.5.2 to 0.5.3

### ISSUE THREAD

**Issue by Hongbo-Miao** [Urigo/angular2-meteor#237]
After updating **angular2-meteor** from 0.5.2 to 0.5.3 (meteor version 1.3.2.3), my app shows a blank page.

My terminal shows;

```
If you notice problems related to these missing modules, consider running:
  meteor npm install --save angular2-meteor
```
which I already did.

My browser console got the error:
```
Uncaught Error: Cannot find module 'angular2-meteor/meteor_component'
```

My code just a "Hello World" codes, nothing more:

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import {Component} from 'angular2/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { MeteorComponent } from 'angular2-meteor/meteor_component';

@Component({
  selector: 'app',
  templateUrl: 'client/app.html'
})
class App extends MeteorComponent {
    constructor() {
        super();
    }
}
bootstrap(App);

```

**Comment by barbatus** [comment]
MeteorComponent is in angular2-meteor directly, i.e., `import {MeteorComponent} from 'angular2-meteor'`. Why not to check out the repo before posting an issue?

**Comment by Hongbo-Miao** [comment]
Thanks for quick response!! It is working again now!
I only checked the full tutorial, forgot to check the the code in this readme file...
