### ISSUE TITLE
Version 0.6.0 of angular2-compilers doesn't compile the template

### ISSUE THREAD

**Issue by watalberto** [Urigo/angular2-meteor#334]
Hi,
I don't test with version 0.5.8 but I can do if you need, for the moment it's working with v.0.5.7
The problem with this last version is the compiled html, my main component looks like:
`@Component({
  selector: 'my-app'...`
but the generated html looks like:
`<html><head>...</head><body>
<my-app>
<html><head>...</head><body>
    <my-app></my-app>
</body>
</html>
</my-app>
</body><html>`

**Comment by derek-fong** [comment]
@watalberto Have you tired [this](https://github.com/Urigo/angular2-meteor#static-resources) after updating to 0.6.0?

**Comment by emilianosantucci** [comment]
@watalberto, the hint from @derek-fong resolve it.
@Urigo, I'm link at this issue for a question: why any static HTML is resolved in `Cannot find module './FILE_NAME.html'.` although is correctly resolved by compilers?
It's tedious during development and I think you already know this issue.
Exist a solution or temporary workaround for that?

Thanks

**Comment by derek-fong** [comment]
@emilianosantucci you might be interested in reading Urigo's comments in Issue #328 

> Yes, those Typescript error are because the way Meteor compiles Typescript.

> these errors will be solved with Typescript 2.0 as described here: https://github.com/Urigo/angular2-meteor/tree/master/atmosphere-packages/css-compiler

**Comment by emilianosantucci** [comment]
Thank you @derek-fong :)

**Comment by watalberto** [comment]
okay @derek-fong I gonna use template instead of templateUrl, and I'll let you know the results.

**Comment by watalberto** [comment]
@derek-fong that was a great solution! many thanks!!
