### ISSUE TITLE
Doesn't work on 1.3.4.1

### ISSUE THREAD

**Issue by gooor** [Urigo/angular2-meteor#316]
Getting `Cannot find module 'angular2-meteor-polyfills/browser'` after just having main.html file with empty body. Nothing I do removes that ...

*Edit*
I have to write it somewhere - am I the only person having tons of problems with angular 2 and meteor - it has so much issues with just old, simple "Hello world" - I know it's beta, but really I can't even start to learn this s....t when it has so many issues :(

**Comment by strobox** [comment]
Also had problems (Socially tutorial + Meteor 1.3.4.1). I've downgraded to 1.3.2.4 temporary. Looks like dependencies conflicts is main reason of troubles.

**Comment by barbatus** [comment]
Install angular2-meteor-polyfills NPM
