### ISSUE TITLE
route config error after upgrade barbarous:typescript from 0.3.1 to 0.3.3

### ISSUE THREAD

**Issue by shalaby** [Urigo/angular2-meteor#292]
Hi, thanks for the hard work for the community, my app was running well till I updated
barbatus:typescript           upgraded from 0.3.1 to 0.3.3
barbatus:typescript-compiler  upgraded from 0.5.12 to 0.6.1
it gives me this error:
`browser_adapter.js:77 Error: Route config should contain exactly one "component", "loader", or "redirectTo" property.`
I am using the deprecated router.

**Comment by barbatus** [comment]
It's certainly not related to the compiler, search by the [error message](https://www.google.com/search?q=Route+config+should+contain+exactly+one+%22component%22%2C+%22loader%22%2C+or+%22redirectTo%22+property&oq=Route+config+should+contain+exactly+one+%22component%22%2C+%22loader%22%2C+or+%22redirectTo%22+property&aqs=chrome..69i57j0.180j0j7&sourceid=chrome&ie=UTF-8) and fix your router configuration.
